src/index.js

Allow for directory listing to not be opened automatically when Browsersync starts (`open: false`).

Parse Browsersync `open` option.

---

src/transformers/index.js
src/transformers/minify.js
src/transformers/replaceStrings.js

This PR adds a Transformer that can do batch find & replace on the final HTML string.
It's configurable through the env config:
```js
cleanup: {
replaceStrings: {
'replace any instance of this exact text': 'with this one',
'\\s?style=""\s?': '',
}
},
}
```
Useful for getting rid of empty attributes or simply replacing placeholder text.
Because the minifier is now no longer needed to remove empty attributes and such, this PR also changes the way you use it, so we no longer always pass the HTML through it. 
You now explicitly enable the minifier, just like with other options:
```js
minify: {
enabled: true, // this is now required in order to use the minifier
minifyCSS: true,
maxLineLength: 500,
collapseWhitespace: true,
processConditionalComments: true, …
```

Replace strings

---

src/index.js

Instead of logging the exception, it should be thrown so it can be properly handled.

Remove console.log

---

src/generators/output/toString.js

This PR refactors the template inheritance to work properly in both CLI and Node.
For any Template1 being `extend`ed by a Template2, you need to make sure to specify the `layout` to extend in Template1.
Also, in order for Maizzle to recursively compile nested Template extends, your Layouts and Templates must use the `{% block template %}{% endblock %}` tag.

Refactor inheritance

---

src/generators/tailwind.js

Maizzle.render() uses the config's purgeCSS "content", on the same way as it uses purgeCSS "whitelist", etc.

Allow customizing purgeCSS "content" when building strings

---

src/index.js

This allows specifying a custom UI port (to mirror the ability to change the default port) or disabling the UI entirely.
See https://browsersync.io/docs/options#option-ui

Include ui browser sync option

---

src/generators/output/toString.js

This PR fixes Nunjucks inheritance as discussed in #98.
Pros:
- you can now use the full power of inheritance in Nunjucks 💪
- not limited to naming your template's main block, `{% block template %}`
Cons:
- can't define `layout` in Front Matter anymore, must use `{% extends "path/to/layout.njk" %}` at the top of every template, after Front Matter
- because every template must specify the layout (or template) it `extends`, we cannot use the 'default layout' functionality anymore

Fix Nunjucks inheritance.

---

src/transformers/posthtmlContent.js

This PR adds support for user-defined content transforms through [`posthtml-content`](https://github.com/posthtml/posthtml-content). 
Use this to do anything you want to content inside elements that you mark with custom attributes.
First, add a `transformContents` object to your Maizzle config:
```js
//config.js
// ...
transformContents: {},
}
```
Each entry in this object is made up of a `key: value` pair.
- `key` represents a custom HTML attribute name
- `value` is a function that accepts a `parameter`, and must return a string. `parameter` is the contents of the tag on which the `key` attribute was used.
```js
//config.js
// ...
transformContents: {
fooreplace: str => str.replace(/foo/g, 'foo bar'),
}
}
```
Template:
```html
<p fooreplace>Here is …
```

PostHTML content transforms.

---

src/generators/output/to-disk.js
src/generators/tailwind.js
test/test-tailwind.js
test/test-todisk.js

This PR adds support for user-defined PostCSS plugins.
You will be able to add your own PostCSS plugins to the Tailwind PostCSS build chain, in your Maizzle environment config:
```js
// config.js
build: {
postcss: {
plugins: [
require('autoprefixer')({/*autoprefixer options*/})
]
}
}
}
```
When merged, this will close #140

Add support for user defined postcss plugins

---

package-lock.json
package.json
src/generators/tailwind.js
test/test-tailwind.js
test/test-transformers.js

This PR adds support for Tailwind CSS 1.4.
In order to ensure email-compatible `background-color` and `color` utilities, this release uses `target: 'ie11'` by default behind the scenes. However, you are free to override it in your `tailwind.config.js`.
You can use Maizzle's `purgeCSS` config options, the `purge` config key from Tailwind, or even a combination of the two. Content sources, as well as PurgeCSS options are collected by Maizzle from both places and merged into a single config object that it uses to purge unused CSS.
This will always run only once, so you don't need to worry about it running twice just because you prefer using Tailwind's config for the PurgeCSS options 👍

Tailwind 1.4

---

src/generators/output/to-disk.js
test/test-todisk.js

This PR adds support for using multiple asset paths:
```js
// config.js
build: {
assets: {
source: ['src/assets/images', 'src/fonts'],
destination: 'assets',
},
// ...
}
}
```

feat(todisk): support multiple asset paths

---

src/index.js

This pull request fixes #231 by adding support for all Browsersync options.
Some defaults are provided, but you can now pass any option to Browsersync from `build.browsersync` inside your `config.js`.

feat: support all browsersync options

---

src/index.js

This PR fixes an issue with events not running on subsequent _template_ saves when using `maizzle serve` to develop locally.
It _did_ work initially right when triggering the command, because we first use the `build()` method to compile all templates, and that correctly passes events you have defined to the `render()` method.
After that, every time you save a template, Maizzle uses the [`render()`](https://maizzle.com/docs/nodejs/) method to compile only _that_ template, resulting in very fast local development. However, when this functionality was [introduced](https://github.com/maizzle/framework/commit/7b78094219e205c802f63ab02476bc3841a73ebc#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R75-R80) in 2.3.0, I forgot about events and how they also need to be passed …

fix: events in serve method

---

src/generators/output/to-string.js
src/generators/posthtml.js
src/transformers/posthtml-mso.js
test/expected/inline.html
test/fixtures/inline.html
test/test-transformers.js

This PR adds support for using Tailwind classes inside `<outlook>` tags. You no longer need to write inline styles there, as long as you have `inlineCSS` enabled in your Maizzle config, it'll just work.
For example this:
```html
<outlook>
<p class="text-center">Example</p>
</outlook>
```
... will be output like this if you have CSS inlining enabled:
```html
```
The way it works is that the `posthtml-mso` plugin now runs after all Transformers, giving the inliner (and other tools) the chance to work with real HTML nodes instead of HTML comments, which is what Outlook conditionals are.

feat(posthtml): add support for tailwindcss in outlook conditionals

---

src/generators/posthtml.js
test/test-tostring.js

This PR adds support for user-defined top-level config objects.
In other words, you can define [variables](https://maizzle.com/docs/layouts/#variables) (a.k.a. `locals`) outside of the `page` object.
Simply add a `locals` object to your `config.js`:
```js
locals: {
company: {
name: 'Spacely Space Sprockets, Inc.'
}
}
}
```
You can access `company.name` directly, no need for the `page` object:
```html
<h1>{{ company.name }}</h1>
```
Alternatively, you can also create a top-level config object by configuring `posthtml-expressions` and passing in `locals` there:
```js
build: {
posthtml: {
expressions: {
locals: {
foo: 'bar'
}
}
}
}
}
```
```html
<p>'foo' is {{ foo }}</p>
```
Note: overwriting the `page` object is not possible, so if you do something like …

feat(posthtml): define top-level locals in config

---

package-lock.json
package.json
src/index.js

This PR reverts the 'hot reload' functionality. After extensive testing, it looks like `bs-html-injector` has some memory leaks that makes it become very slow. Most importantly, it also does bad diffs, mangling the HTML in the browser preview.
This means developing with `maizzle serve` will do full page refreshes, just like before.

revert: hot reload

---

package-lock.json
package.json
src/generators/posthtml.js

This PR fixes an issue with PostHTML options not being used when rendering Components.
Fixes #417.

fix: use posthtml options in components

---

package-lock.json
package.json
src/generators/tailwindcss.js
test/expected/tailwind/default.css
test/test-tailwind.js

Fixes #422 
This PR changes the way Tailwind is compiled internally.
- upgrade Tailwind to latest version
- remove `@fullhuman/postcss-purgecss`
- use Tailwind's own `purge` option instead of a custom strategy
To use JIT, you need to also specify the `purge` option in your `tailwind.config.js`, **in simplified array syntax**:
```js
mode: 'jit',
purge: [
'src/**/*.*',
],
// ...
}
```

Refactor Tailwind CSS purging

---

src/generators/tailwindcss.js
src/index.js

- sets `TAILWIND_MODE = watch` when using JIT, fixing an issue with new classes not being generated when developing locally
- uses correct template extention when developing locally (fixes #423)

Refactor serve

---

src/generators/output/to-disk.js
src/index.js
test/test-todisk.js

This PR fixes an issue with files not being output with the correct extension, so you can use non-HTML files when developing and have them output with the `.html` extension so you can preview them in the browser.
Fixes #485

fix: destination extension

---

src/generators/output/to-disk.js
src/index.js
xo.config.js

This PR fixes some issues with destination paths.
- fixes #497 
- fixed an issue with template `permalink ` in Front Matter not being respected when using `maizzle build` (with no `env`)
- fixed an issue with file types not being correctly excluded
- fixed an issue where the original file was not cleaned up from the destination path when using non-HTML source templates

fix: output paths

---

src/generators/tailwindcss.js

Maizzle will try to automatically load `src/css/tailwind.css` from your current working directory, so you don't need to define the path to it in your `config.js` anymore:
```diff
build: {
-    tailwind: {
-      css: 'src/css/tailwind.css',
-    },
},
}
```
If the file does not exist, Maizzle will compile Tailwind using `@tailwind components; @tailwind utilities;` using your `tailwind.config.js`.

feat: autoload tailwind.css if it exists

---

package.json
src/generators/config.js
src/generators/tailwindcss.js
src/index.js
src/transformers/transform.js
src/utils/helpers.js
test/stubs/config/config.js
test/stubs/config/config.maizzle-ci.js
test/test-config.js
test/test-todisk.js

This PR refactors watchers when using `maizzle serve`.
Changes to Maizzle `config.*.js` files now also trigger a rebuild and browser refresh.
Changes to `src/` files other than templates now properly trigger a rebuild and browser refresh.
File events, like adding/removing files, should also rebuild & refresh the browser.

Refactor watchers

---

src/generators/output/to-disk.js
src/generators/plaintext.js

This PR fixes an issue with using directory destination paths for plaintext files.
Fixes #469

fix: generating plaintext files with custom destination path

---

src/generators/output/to-disk.js
src/generators/plaintext.js

This PR adds support for generating plaintext files only for those template sources that opt in. Now, when using multiple template sources, Maizzle will first check if the currently-being-built templates source has enabled plaintext.
Basically, you can now do this:
```js
// config.js
build: {
templates: [
{
source: 'src/templates',
destination: {
path: 'build-1',
},
plaintext: true // build-1 folder only: output plaintext files next to the HTML counterparts
},
{
source: 'src/templates',
destination: {
path: 'build-2',
},
// build-2 folder only: output plaintext files in the `plaintext` subdirectory, with custom extension
plaintext: {
destination: {
path: 'build-2/plaintext',
extension: 'rtxt'
}
},
},
// plaintext won't be generated in the `build-3` directory, because we …
```

feat: generate plaintext on a template source basis

---

package-lock.json
src/generators/output/to-string.js
test/fixtures/basic.html
test/test-todisk.js
test/test-tostring.js

This PR fixes an issue with the build breaking if you didn't have front matter added to your HTML.
That can happen if you just have something like this, that doesn't even extend a layout:
```html
<!doctype html>
<html>
<head>
<title>test></title>
</head>
<body>
<div>test</div>
</body>
</html>
```
... the build will fail because `posthtml` will receive `undefined` when we try to parse expressions inside a template's front matter:
https://github.com/maizzle/framework/blob/17c9c18baa9559f3becff568be80b4c4bd9d4e00/src/generators/output/to-string.js#L24
Using the HTML in the example above, `fm(html).frontmatter` will be `undefined`, which will cause `Tokenizer.parse` in `htmlparser2` to throw a `TypeError`:
```sh
TypeError {
message: 'Cannot read property \'length\' of undefined',
}
```

fix: missing frontmatter breaks posthtml

---

.github/workflows/nodejs.yml
src/generators/tailwindcss.js
test/stubs/tailwind/preserve.html
test/test-tailwind.js

This PR refactors the way we handle content sources:
- use paths as recommended in the Tailwind CSS docs
- add back template source paths only when they're defined (i.e. when using the `render` method they'd be `undefined`)
- update tests

refactor: tailwindcss content sources

---

src/generators/output/to-disk.js
test/test-todisk.js

BREAKING: this PR drops support for specifying `plaintext` as a top-level Maizzle config.
In order to generate plaintext for a template, you must now either:
```diff
build: {
templates: {
source: 'src/templates',
destination: {
path: t.context.folder,
},
+    plaintext: true,
},
},
- plaintext: true,
```
```html
---
plaintext: true
---
<extends src="src/layouts/main.html">
<block name="template">
...
</block>
</extends>
```

refactor: use plaintext config only from template config

---

src/index.js

This PR adds a new build option that allows disabling the console clearing functionality.
To use it, simply add this to the `build` config object:
```diff
build: {
+  console: {
+    clear: false,
+  }
}
}
```
Note: a CLI command option will be available starting with `@maizzle/cli@1.5.0`.
Fixes #544

feat: allow disabling console clearing

---

src/generators/output/to-disk.js
test/test-todisk.js

This PR: 
- adds support for defining `templates.source` as a function
- supports defining `templates.source` as either a string or an array
For example, you can now do something like this:
```js
build: {
templates: {
source: () => ['src/some/templates', 'src/other/templates'],
// ...
}
}
}
```
Closes #560

refactor template source

---

src/generators/output/to-disk.js
test/test-todisk.js

Add support for defining `templates.source` as an array, i.e.:
```js
build: {
templates: {
source: ['src/some/templates', 'src/other/templates'],
// ...
}
}
}
```

refactor template source paths

---

src/generators/output/to-disk.js
src/generators/tailwindcss.js
test/test-todisk.js

This PR exposes the Maizzle `config` object to your template `source` when used as a method.
For example, you could do this in your `config.js`:
```js
build: {
customSources: ['src/templates', 'some/path/templates'],
templates: {
source: config => {
return config.build.customSources
},
// ...
}
}
```
The `source` function must return a string path or an array of string paths.
These paths will be automatically added to Tailwind's `content.files` list, so selectors in files there will be preserved/generated.
Closes #560

feat: expose config to template sources as function

---

src/generators/output/to-disk.js
src/generators/tailwindcss.js
test/test-tailwind.js

This PR adds support for file path sources, so you can compile just one template when developing locally with the `maizzle build` command:
```js
build: {
templates: {
source: 'src/templates/index.html',
destination: {
path: 'build_local',
},
},
}
}
```

feat: support file path sources

---

src/generators/output/to-disk.js
src/generators/tailwindcss.js
src/transformers/transform.js
test/test-tailwind.js

This fixes a regression in the previous release, which resulted in the user's `tailwind.css` not being used.
Now everything should work as expected:
1. if `src/css/tailwind.css` exists -> only its contents are compiled
2. if it's missing, `'@tailwind components; @tailwind utilities;' + yourcss` is compiled
In both cases, `tailwind.config.js` from the current dir will be used; Maizzle falls back to Tailwind's default config if this is unabailable. (note: this is for local dev, if using programmatically the Tailwind config is passed as a parameter).
`yourcss` in point 2 is used when calling `Tailwind.compile` internally, and is the content of `<style postcss>` or `<style tailwindcss>` tags in your template (so you can use Tailwind syntax in there).

fix: tailwind compilation with user css file

---

src/transformers/sixHex.js
test/test-transformers.js

This PR fixes an issue with the sixHex transformer that was causing HEX codes from text content to be expanded from 3 to 6 digits.
Fixes #668

refactor: sixhex transformer

---

bin/maizzle
package-lock.json
package.json

This PR adds a `maizzle` executable to the framework, so you can run the npm build scripts without having to install the Maizzle CLI globally. With this change, getting started with Maizzle is now as easy as:
```sh
npx degit maizzle/maizzle my-project
cd my-project
npm install
npm run dev
npm run build
```

feat: add maizzle executable

---

src/transformers/prettify.js
test/expected/posthtml/component.html
test/expected/transformers/atimport-in-style.html
test/expected/transformers/preserve-transform-css.html
test/expected/useConfig.html
test/fixtures/posthtml/component.html
test/test-posthtml.js
test/test-todisk.js
test/test-transformers.js

This PR refactors the `prettify` Transformer so that it runs only when you specifically enable it.
It is considered enabled if you set `prettify: true` or `prettify: { /* non-empty object */ }` in your `config.js`.

refactor: make prettify transformer opt-in

---

src/generators/output/to-string.js

This PR fixes an issue where we were evaluating expressions defined in front matter twice, which lead to issues with ignoring expressions through `@{{ }}` syntax.
You can now basically escape expressions in front matter without having to do it in the template/layout as well:
**src/layouts/example.html**
```html
Greeting escaped in front matter, rendered as usual in layout: {{ page.greeting }}
<block name="template"></block>
```
**src/templates/example.html**
```html
---
greeting: "Hello @{{ firstname or 'friend' }}"
---
<extends src="src/layouts/example.html">
<block name="template">
<div>
{{ page.greeting }}
</div>
</block>
</extends>
```
Result:
```html
Greeting escaped in front matter, rendered as usual in layout: Hello {{ firstname or 'friend' }}
<div>
Hello {{ firstname or 'friend' …
```

fix: ignoring expressions in front matter

---

src/commands/serve.js

This PR enables the tailwind config to be passed directly as object to the serve() function. Currently it won't work because the tailwind config object would be added as path to `globalPaths`
```javascript
Maizzle.serve("local", {
build: {
...someMaizzleConfig,
tailwind:{
config:{
...theTailwindConfigAsObject
}
}
});
```

fix: don't watch tailwind config if object in serve()

---

src/generators/output/to-disk.js
test/test-todisk.js

This PR adds `config.build.current`, an object containing a parsed path of the currently-processed template:
```js
{
root: '',
dir: 'build_production',
base: 'example.html',
ext: '.html',
name: 'example'
}
```
Since Maizzle copies the source files to destination and then compiles them there, the parsed path is your `build.templates.destination.path`, hence the `build_production` directory.
Also, this is only available when using the CLI with `maizzle build` - there's no source file path when using the API.

feat: config.build.current

---

src/generators/posthtml.js

This PR fixes an issue where expressions options were not being passed down to components.

fix: pass expressions options to components

---

src/generators/output/to-disk.js

This PR fixes an issue where providing a pre-compiled CSS string in order to skip Tailwind CSS compilation was not working because we were checking for it in the wrong place.
You may now do this in your Maizzle `config.js` if you want to skip Tailwind CSS compilation:
```js
build: {
tailwind: {
compiled: '',
}
}
}
```

fix: tailwind compiled string path

---

src/transformers/urlParameters.js
test/test-transformers.js

This PR fixes #771, where if you didn't provide the `_options` object to the `urlParameters` transformer in addition to the parameters that you wanted apended to URLs, the build would fail.

fix: don't require _options for urlParameters transformer

---

src/generators/output/to-disk.js
src/generators/postcss.js
src/generators/tailwindcss.js
test/test-postcss.js
test/test-tailwindcss.js

This PR changes the way an error is thrown when Tailwind CSS or PostCSS compilation fails by removing the `console.error` and throwing a `SyntaxError` instead of a plain `Error`.
Given something like this in your `tailwind.css` file:
```css
.example {
@apply test;
}
```
The build will now fail with a `SyntaxError` that makes clearer where the issue occured:
```
✖ CssSyntaxError: C:\projects\maizzle\src\css\tailwind.css:2:3: The `test` class does not exist. If `test` is a custom class, make sure it is defined within a `@layer` directive.
1 | .example {
> 2 |   @apply test;
|   ^
3 | }
4 |
```

refactor: tailwindcss compilation error

---

src/generators/tailwindcss.js
test/test-tailwindcss.js

This PR fixes a performance issue where we always included `./src/**/*.*` in the `content` array when compiling Tailwind CSS.
This not only included a very broad pattern, but started significantly slowing builds down as more files were added to the `src` folder. It was especially noticeable when image files were added to `./src/assets`.
Now, the default `content` sources are:
```js
content: {
files: [
'./src/components/**.html',
'./src/layouts/**.html',
{raw: html, extension: 'html'}
]
}
```
... where `html` is the HTML string currently being processed.
If you add your own `content` key to `tailwind.config.js`, this will be overwritten to:
```js
{
files: [
...config.content,
{raw: html, extension: 'html'}
]
}
```
... meaning that you need to make sure to also add any paths to Components …

fix: tailwindcss content sources

---

src/transformers/filters/index.js

This PR fixes #782, an issue where the `safeClassNames` transformer could not be disabled even when it was correctly set to `false` in the config.

fix: disabling safeClassNames transformer

---

src/transformers/removeInlineBackgroundColor.js
src/transformers/removeInlineSizes.js
src/transformers/removeInlinedSelectors.js
src/transformers/sixHex.js
src/utils/helpers.js
test/test-transformers.js

This PR refactors attribute parsing in some transformers to solve an issue where attributes with no value were being quoted even when PostHTML was configured with the `recognizeNoValueAttribute` option.
Basically, if you had this in your `config.js`:
```js
build: {
posthtml: {
options: {
recognizeNoValueAttribute: true
}
}
}
}
```
... Maizzle was compiling this:
```html
<a href="report.pdf" download>
Download report
</a>
```
... to this:
```html
<a href="report.pdf" download="">
Download report
</a>
```
Notice the extra `=""`. 
This PR ensures that attributes are output as they were written (as long as you have set the `recognizeNoValueAttribute` option).

refactor: parsing attributes in transformers

---

src/generators/posthtml.js

This PR enables `recognizeNoValueAttribute` by default so that attributes with no value are not appended a `=""` by PostHTML.

refactor: posthtml default options

---

src/generators/plaintext.js
src/generators/posthtml/defaultConfig.js
src/generators/posthtml/index.js
src/transformers/attributeToStyle.js
src/transformers/baseUrl.js
src/transformers/extraAttributes.js
src/transformers/filters/index.js
src/transformers/markdown.js
src/transformers/posthtmlMso.js
src/transformers/preventWidows.js
src/transformers/removeAttributes.js
src/transformers/removeInlineBackgroundColor.js
src/transformers/removeInlineSizes.js
src/transformers/removeInlinedSelectors.js
src/transformers/replaceStrings.js
src/transformers/safeClassNames.js
src/transformers/shorthandInlineCSS.js
src/transformers/sixHex.js
src/transformers/urlParameters.js
test/expected/transformers/base-url.html
test/test-transformers.js

This PR adds default PostHTML options, helping fix an issue with valueless attributes like `<div data-id>` being rewritten to contain an empty value, i.e. `<div data-id=""`.

refactor: use default posthtml options

---

package-lock.json
package.json
src/transformers/removeAttributes.js
test/test-transformers.js

This PR refactors the `removeAttributes` transformer by replacing `posthtml-remove-attributes` with a custom PostHTML plugin that can also respect PostHTML options like `recognizeNoValueAttribute` if present.
As a result, the `posthtml-remove-attributes` dependency has been removed.

refactor: remove attributes transformer

---

src/generators/tailwindcss.js

This PR fixes an issue with the default Tailwind CSS content sources when a user customized root paths for components and layouts. If you change/add `build.components.root` or `build.layouts.root` in your `config.js`, Tailwind will now correctly use those paths when generating CSS.

fix: respect config.js root paths in tailwindcss content sources

---

src/transformers/removeInlinedSelectors.js
test/test-transformers.js

This PR fixes an issue where empty `style` tags started being output in the compiled HTML after some updates to `removeInlinedSelectors`.

fix: remove empty style tags

---

src/transformers/filters/index.js
src/transformers/safeClassNames.js

This PR helps fixe an issue with using expressions inside `class=""` attributes, where something like `class="{{ var }}"` was being compiled to `class=" var "` because the `safeClassNames` transformer was removing `{` and `}` from class names by default.

refactor: add default replacements for safeClassNames

---

src/generators/plaintext.js
test/stubs/plaintext/plaintext.html
test/test-todisk.js

This PR fixes #780 by completely removing any `<not-plaintext>` tags from the HTML used to generate the plaintext version.

fix: ensure href values in not-plaintext tags are removed

---

src/transformers/inlineCss.js
src/transformers/removeInlineSizes.js
test/test-transformers.js

This PR fixes some issues with CSS inlining:
- fixed an issue where using lowercase tag names in `inlineCSS` did not work
- fixed an issue where `styleToAttribute` was not being applied

[4.x] Fixes issues with the inlineCSS transformer

---

src/transformers/filters/index.js
test/test-transformers.js

This PR adds the ability to completely disable filters in Maizzle by setting the option to `false` in your `config.js`:
```js
filters: false,
}
```

feat: disable filters

---

src/generators/postcss.js
test/test-tostring.js
test/test-transformers.js

Forgot to make the new `shorthandCSS` option available to this Transformer too.
Added now, so you can do this:
```html
<style postcss>
.padded {
@apply py-2 px-4;
}
</style>
```
... and, as long as you have `shorthandCSS: true` in your `config.js`, get this:
```html
<style>
.padded {
padding: 8px 16px;
}
</style>
```
Of course if you have `shorthandCSS: false`, it will not merge the rules and you'll get:
```html
<style>
.padded {
padding-top: 8px;
padding-bottom: 8px;
padding-left: 8px;
padding-right: 8px;
}
</style>
```

Add `shorthandCSS` to `postcss` transformer

---

src/transformers/baseUrl.js

This PR fixes an issue where the string `undefined` was being prepended to VML src paths if you were using object syntax for `baseURL`, but somehow forgot to include the `url` key. This wasn't an issue for the rest of the markup, just when VML code was processed, so this makes the behavior consistent.
Also, `baseUrl` will also work now, just in case you were tired and made a typo :)

Don't add `undefined` to VML paths if `baseURL.url` is missing

---

src/generators/config.js

When using Maizzle in a project with "type": "module", the configuration file `config.js` is treated like an ESM module, which causes an error (since it's written in CommonJS). To fix this, it should be renamed to `config.cjs`, but it doesn't seem like Maizzle supports this just yet (since it relies on Node's auto-extension resolution algorithm, which doesn't work for the `.cjs` extension).
This PR just adds some explicit checks for `.cjs` files in the configuration loader so that Maizzle correctly loads configuration files that end with a `.cjs` extension.
Let me know if you have any questions!

feat: support cjs extension for config

---

src/transformers/baseUrl.js
test/test-transformers.js

This PR fixes an issue with `baseURL` defaults when it is configured as an object.
Specifically, in this case the `url` was not being appended to `<style>` tags or inline CSS, you had to enable them manually, i.e.:
```js
baseURL: {
url: 'https://example.com/images/',
tags: ['img', 'source'],
inlineCss: true,
styleTag: true,
},
```
Now you can just do this and it will work:
```js
baseURL: {
url: 'https://example.com/images/',
tags: ['img', 'source']
},
```

fix: baseURL defaults when configured as object

---

src/generators/output/to-disk.js
test/test-todisk.js

This makes the build error message less confusing when you didn't have a `build.templates.source` defined in the config.
So if you ran `maizzle build imaginary` but had no `config.imaginary.js`, you would have seen this cryptic message:
```
$ maizzle build imaginary
✖ Cannot read properties of undefined (reading 'source')
```
Now you'll get a better error message:
```
$ maizzle build imaginary
✖ No template sources defined in `build.templates`, check your config.imaginary.js file
```

fix: templates source error

---

src/generators/output/to-disk.js
src/generators/output/to-string.js
src/generators/tailwindcss.js
src/transformers/filters/index.js
test/test-tailwindcss.js

This PR refactors the Tailwind CSS generator function to accept a single object as a parameter, fixing a bug where your custom Tailwind config object was not being used when rendering emails through the Maizzle API.
To give an example, the following would have generated `bg-emerald-200` as `#a7f3d0` instead of `emerald` like defined in the custom Tailwind config object passed to the `render` function:
```js
const Maizzle = require('@maizzle/framework')
let template = `---
title: 'Hello World'
---
<x-main>
<fill:template>
<div class="bg-emerald-200">
Sample
</div>
</fill:template>
</x-main>
`
const tailwindConfig = {
theme: {
extend: {
colors: {
emerald: {
200: 'emerald',
},
},
},
},
corePlugins: {
preflight: false,
backgroundOpacity: false,
},
}
async function main() {
const { html } = …
```

Refactor Tailwind CSS generator to accept parameters through an object

---

src/generators/output/to-disk.js
src/utils/helpers.js

This PR changes replaces the custom `asyncForEach` method that we used to iterate over arrays asynchronously with the native `for await...of` statement.

Use native `for await` instead of custom asyncForEach method

---

src/commands/serve.js
test/test-serve.js
test/test-todisk.js

This PR:
- fixes an issue where saving a template file while developing locally was outputting it in a wrong location 804b100
- ensures an error is thrown when local server rebuilds fail e317e4c

Fix paths and throw errors in local server

---

src/generators/posthtml/index.js

This PR enables an alternative `<for>` loop tag which can be used instead of `<each>`:
```xml
<for loop="item, index in [1,2,3]">
{{ item }}
</for>
```

feat: add `for` as an alternative loop tag name

---

src/generators/posthtml/defaultComponentsConfig.js
src/generators/posthtml/index.js
src/generators/tailwindcss.js
test/test-posthtml.js
test/test-tailwindcss.js
test/test-tostring.js
xo.config.js

This PR:
- fixes an issue where utilities in Templates inside directories with dots in their name (like `src/templates/test.com`) were not being generated
- adds `{raw: html, extension: 'html'}` to Tailwind's `content.files` only if `html` was passed to the Tailwind compiler - this happens/is needed only when using Maizzle programmatically, so we removed it for normal use cases

Fix TailwindCSS content paths

---

src/generators/posthtml/index.js

This PR fixes an issue with the default Components options that was causing props data mismatching, resulting in props not using the defaults they were set to.

fix: default components options

---

src/transformers/removeUnusedCss.js

This PR changes the way `removeUnusedCSS` behaves, allowing you to completely override its selectors safelist from your `config.js`. This was necessary so that email client targeting selectors do not show up in all of your project's templates when you just want to use a one-off. They would normally show up because Tailwind CSS is compiled once for all templates, and then is purged on a template-basis.
Maizzle won't remove these selectors in the first pass, but with this change you can now run a quick second pass to remove unnecessary client targeting selectors from templates that don't need them:
```js
// config.production.js
const {removeUnusedCSS} = require('@maizzle/framework')
// ...
events: {
// Run removeUnusedCSS again, this time overriding the `whitelist` option …
```

refactor: allow overriding email comb selector safelist

---

src/generators/tailwindcss.js

This PR fixes an issue with `content` patterns for Tailwind CSS when specifying multiple file extensions for Maizzle templates.
Basically if you had something like this:
```js
build: {
templates: {
filetypes: ['html', 'yaml'],
source: 'src/templates',
}
}
}
```
The automatically-generated `content` path was:
```
'src/templates/**/*.html,yaml'
```
While Tailwind doesn't warn about it, the pattern won't work to search in all `html` and `yaml` files at that location, resulting in some CSS not being generated. With this fix, it will be correctly generated to:
```
'src/templates/**/*.{html,yaml}'
```

Tailwind CSS multiple file extension content pattern

---

src/transformers/filters/index.js
src/transformers/safeClassNames.js
test/test-transformers.js

This PR changes the way the `safeClassNames` Transformer runs by default.
It now:
- doesn't run when `env` is `local` (developing locally, like with `maizzle serve`)
- exception: will run locally if explicitly set to `true`
- doesn't run if explicitly disabled (`safeClassNames: false`)
This makes it a little easier to debug when developing locally and inspecting the code - by default now you get to see the Tailwind classes exactly as you wrote them.

Defaults for running `safeClassNames`

---

src/transformers/filters/index.js

This PR fixes an issue where the default (web) Tailwind config was used inside `<style tailwindcss>`, instead of the local `tailwind.config.js`.

Fix using local Tailwind config in style filter

---

src/transformers/extraAttributes.js

This changes the default `role` attribute value added to `<table>` elements from `presentation` to `none`, as it does the same thing and is 8 characters shorter, resulting in a smaller HTML size.
From [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/none_role):
> The `none` role is a synonym for the [presentation](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/presentation_role) role; they both remove an element's implicit ARIA semantics from being exposed to the accessibility tree.

refactor: prefer role none over presentation

---

src/generators/output/to-disk.js

This PR exposes the `config` object as the second parameter of the `afterBuild` event function, so you can read it like this:
```js
// config.production.js
// ...
events: {
afterBuild(files, config) {
const env = config.env
// do stuff with env
}
}
}
```

feat: expose config in afterBuild event

---

package-lock.json
package.json
src/index.d.ts
tsconfig.json

From: https://github.com/maizzle/framework/issues/1052
Please suggest changes (if any) 
All this has been taken from the documentation.

Typescript typings

---

src/commands/serve.js
src/generators/config.js
src/generators/output/to-disk.js
src/generators/output/to-string.js
src/generators/plaintext.js
src/generators/posthtml/index.js
src/generators/tailwindcss.js
src/transformers/attributeToStyle.js
src/transformers/baseUrl.js
src/transformers/extraAttributes.js
src/transformers/filters/index.js
src/transformers/markdown.js
src/transformers/posthtmlMso.js
src/transformers/prettify.js
src/transformers/preventWidows.js
src/transformers/removeAttributes.js
src/transformers/removeInlineBackgroundColor.js
src/transformers/removeInlineSizes.js
src/transformers/removeInlinedSelectors.js
src/transformers/removeUnusedCss.js
src/transformers/safeClassNames.js
src/transformers/shorthandInlineCSS.js
src/transformers/sixHex.js
src/transformers/urlParameters.js
src/utils/helpers.js
test/test-misc.js

Switched to using a custom function based on `lodash.mergeWith` instead of `lodash.merge`, to avoid overwriting array values when merging objects ([reference](https://github.com/lodash/lodash/issues/5384)). Fixes #1057.
Given this:
```js
merge(
{foo: ["a", "b", "c"]},
{foo: ["d"]}
)
```
Previously: 
```js
{
foo: ["d", "b", "c"]
}
```
Now:
```js
{
foo: ["a", "b", "c", "d"]
}
```

fix: object merging

---

src/commands/serve.js
src/generators/config.js
test/stubs/config/maizzle.config.test.js
test/test-config.js
test/test-todisk.js

Fixes #1077.
This PR adds support for `maizzle.config.js` configuration file names, similar to Tailwind's `tailwind.config.js`.
Here's an overview of Maizzle commands and the config file names they'll use:
| **Command**         | **Config file name**                         |
|---------------------|----------------------------------------------|
| maizzle build       | config.js <br> maizzle.config.js             |
| maizzle build {env} | config.{env}.js <br> maizzle.config.{env}.js |
| maizzle serve {env} | config.{env}.js <br> maizzle.config.{env}.js |
Maizzle will try to look for `maizzle.config.js` first, falling back to `config.js`.
We're now configuring `chokidar` to wait for files to be written to disk. This should help prevent the dev server crashing when you add files to watched …

feat: add support for maizzle.config.js files

---

package-lock.json
package.json
src/index.d.ts
src/transformers/prettify.js
test/expected/components/kitchen-sink.html
test/fixtures/components/kitchen-sink.html
test/test-posthtml.js
test/test-transformers.js

This PR changes the `prettify` transformer from `pretty` to `prettier` (which makes sense if you think about it 😂).
Main reason behind this is for HTML/MSO comments to be correctly indented too.
Closes #1071.

feat: use prettier for prettify transformer

---

src/transformers/prettify.js

Fixes #1152 
This PR removes the custom regexes that keep causing issues in the `reFormat()` function of the prettifier.
Using `embeddedLanguageFormatting: 'off'` is enough to fix things like `&quot;` in font stacks, or inline CSS font stacks being output on separate lines.

fix: remove custom regexes in prettier output reformatting

---

src/transformers/prettify.js
test/expected/components/kitchen-sink.html
test/expected/transformers/prettify.html
test/fixtures/transformers/prettify.html
test/test-transformers.js
xo.config.js

Fixed a bunch of issues with `prettier` formatting:
- use default `embeddedLanguageFormatting` (`auto`)
- rewrite closing slash only for known self closing tags
- fix `style=""` attribute values broken on multiple lines
- fix broken `</pre>` closing tags (`>` on separate line)
- undo escaping `'` to `&quot;` in attribute values
- fix some attributes and closing `>` being broken on to a separate line
Fixes #1156 
Fixes #1158

fix: prettify formatting issues

---

package-lock.json
package.json
src/index.d.ts
src/transformers/prettify.js
test/expected/components/kitchen-sink.html
test/fixtures/components/kitchen-sink.html
test/test-posthtml.js
test/test-transformers.js

This PR reverts the use of `prettier` instead of `pretty` for the `prettfy` Transformer.
`prettier` is just too opinionated and has many formatting issues that we were constantly having to fight through regex replacements, which is not ideal. It's also a bit slower than `pretty`, and the only gain was that it sometimes correctly indented MSO comments.
We will continue to look for other ways of indenting MSO comments, but have taken the decision to go back to `pretty`.
Fixes #1160

revert: use prettier for `prettify` transformer

---

src/commands/serve.js

I would like to fix an issue related to serving build templates with a nested directory structure.
The current implementation fails when dealing with templates organized in nested directories and configured with `templates` as `Array`, during the `serve` command rebuild process of nested template files.
I propose to make the matching of a file to a template source using `String.prototype.includes()` function instead of strict equality (`===`).
```
// Simplified monorepo directory structure with shared packages for different projects
├───projects
│   ├───project-1
│   │   └───maizzle // <-- config.js
│   │       └───templates
│   │           ├───p1-1
│   │           └───p1-2
│   └───project-2
└───shared-packages
├───package-A
│   └───templates  // ✅ 'serve' rebuild of files from …
```

fix: serve build templates array with nested directory structure

---

src/generators/posthtml/index.js

Fixes the order in which expressions options are merged, so that options defined in `build.posthtml.expressions` will work.

fix: expressions config merging order

---

src/commands/build.js
src/generators/output/to-disk.js
test/test-todisk.js

This PR fixes #1255, an issue where the process was not correctly exiting because of an error that was being caught, but not thrown.

fix: throw if a template cannot be rendered

---

src/transformers/replaceStrings.js
test/transformers.test.js

Hi
This adjustement aims to let the replacement string make use of the capturing group in the regex.
In the version 4, replace strings transformers allows us to replace (1) by <sup>(1)</sup>.
Which is not the case in the version 5, i see it as a regression because i personnally used it in that way but maybe it was intended.
In my PR choosed to detect if the replacement string contains a capturing group reference in order to not have the overload of regex replacement if it's not wanted.
Thank for your time and this project !

Allow capturing groups replacement in replaceStrings.js

---

src/generators/render.js
test/render.test.js
types/events.d.ts

can just import and use `render()` instead

revert: exposing posthtml compiler in events

---

src/posthtml/index.js
test/render.test.js
test/stubs/components/list.html

Hi!
The expression configuration in build.expression, is not merged correctly just before rendering.
In my use case i want te remove locals scripts, and on the V5 nothing is removed.
After some investigation i saw that the merge with the locals key in expression config was not done properly.
I added some test that you can check. Maybe you'll want this test not to be in the component loading test. Tell me if you want me to add a new test.
Thanks for your time once more.

Fix PostHTML expression config

---

types/build.d.ts

Adds type definitions for `build.current` so that we get autocomplete when accessing it in events.
Closes #1322

`build.current` types

---

src/commands/build.js
test/build.test.js
types/build.d.ts

Copy directory structures correctly based on content glob paths in user's config.

fix: create correct build output paths

---

src/server/index.js
src/server/routes/index.js

This PR solves issue when the filename contains space, or any other URL encoded symbol.

fix: error when filename has a space
