src/generators/output/toString.js
=> Use Nunjucks extends in render()

src/generators/output/toString.js
=> Make opts.tailwind.css optional in render()

.eslintrc.yml, package-lock.json, package.json, src/generators/config.js, src/generators/output.js, src/generators/output/toDisk.js, src/generators/output/toString.js, src/generators/tailwind.js, src/index.js, src/nunjucks/index.js, src/nunjucks/tags/component.js, src/transformers/addURLParams.js, src/transformers/applyBaseImageUrl.js, src/transformers/applyExtraAttributes.js, src/transformers/index.js, src/transformers/inline.js, src/transformers/minify.js, src/transformers/posthtml.js, src/transformers/prettify.js, src/transformers/removeInlineBgcolor.js, src/transformers/removeInlineSizes.js, src/transformers/removeUnusedCSS.js, src/transformers/replaceStrings.js, src/transformers/sixHEX.js
This PR DRYs up the `toDisk()` method by refactoring it to (re)use `toString()` for rendering templates.
It'll also make it easier to add tests to Maizzle ✌
=> Refactor todisk()

src/generators/output/toString.js
This PR adds a bunch of lifecycle hooks to the `render()` function.
You can pass them inside the options object that you normally pass:
```js
const Maizzle = require('@maizzle/framework')
Maizzle.render('some string...',  {
tailwind: {},
maizzle: {},
beforeRender(nunjucks, config) {
// do stuff with nunjucks environment and config
},
}).then(html => console.log(html))
```
- `afterConfig(config)`
This runs right after your template config is computed and it exposes the config so you can further customize it.
- `beforeRender(nunjucks, config)`
Runs just before the template is rendered with Nunjucks. You can use `nunjucks` to add filters or globals, and you can also modify the config.
- `afterRender(html, config)`
Runs after the template has been rendered. `html` is the compiled email …
=> Initial lifecycle hooks.

package-lock.json, package.json, src/generators/tailwind.js, src/utils/helpers.js, test/test-tailwind.js
=> fix(tailwind): pick up config changes when watching files

package.json, src/generators/output/to-disk.js, src/generators/output/to-string.js, src/generators/tailwind.js, src/transformers/transform.js, test/expected/email-comb.html, test/expected/inline.html, test/expected/minify.html, test/expected/prettify.html, test/fixtures/transform.html, test/stubs/main.css, test/test-tailwind.js, test/test-transformers.js, xo.config.js
This PR refactors the Tailwind generator into a single reusable function and fixes #169's root cause, so we don't need to modify that transformer.
=> Refactor tailwind

src/generators/output/to-disk.js, test/test-todisk.js
=> fix(generators): read plaintext option correctly from template config

src/generators/tailwindcss.js
=> fix: using custom tailwind plugins

src/generators/output/to-disk.js
=> fix(todisk): compile with default tailwind directives

src/index.js, src/utils/helpers.js
=> feat: clear console when developing locally

src/index.js
[Issue](https://github.com/maizzle/framework/issues/605)
- Only initialize BroswerSync once, when needed 9f6375d6d0f1785c90bc6e022d9de830210a3793
This to avoid unnecessary environment issues when trying to run `Maizzle.render()` in environments that purge unused node modules (ie, Vercel Serverless function environment)
See [issue](https://github.com/maizzle/framework/issues/605) for more details.
Run unit tests and/or give broswersync a spin 
**Expectation:** BrowserSync should continue to work as expected
=> Lazy Init broswersync

src/generators/output/to-string.js, test/expected/useConfig.html, test/fixtures/useConfig.html, test/test-todisk.js, test/test-tostring.js
=> feat: use config file in render method if available

src/transformers/baseUrl.js
=> Add Check for null

package-lock.json, package.json
=> build(deps): bump tailwindcss from 3.1.2 to 3.1.3

src/transformers/removeInlinedSelectors.js
This PR adds a fix for cases when the build would break because the CSS clean-up couldn't find a node match through a CSS selector. One such case was with the `@tailwindcss/typography` plugin, as detailed in #726.
=> fix: skip match helper error

package-lock.json
=> Revert "build(deps): bump webpack from 5.74.0 to 5.76.1"

src/index.d.ts
This PR fixes some types, adds new ones, and improves the JSDoc on existing types.
=> refactor: types

src/transformers/prettify.js
=> fix: don't remove space before style attribute

package-lock.json, package.json, test/test-transformers.js
=> build(deps): bump posthtml-attrs-parser from 0.1.1 to 0.1.2

src/transformers/replaceStrings.js, test/transformers.test.js
Hey,
This is me again, you will laugh.... It wasn't working on multiple same replacement.
I tried to prevent using String.replace all the time but it wasn't working as intended, so i kept it like this.
I also added a test to check this specific case.
=> Fix multiple same replacement

src/commands/build.js, src/server/index.js, types/build.d.ts
Implements TODO feature to support an array of objects with source and destination in static files configuration.
=> feature: support an array of objects with source and destination for static files
